---
title: "Figure types"
subtitle: "2025-01-30"
---

# Prelude

# Overview

## Announcements

## Last time...

*Making data*

---

::: {.callout-important}
## Your turn
A set of data about self-reported favorite colors is of what type [@Stevens1946-sh]?

A. Ratio</br>
B. Ordinal</br>
C. Nominal/Categorical
:::

---

::: {.callout-important}
## Your turn
What kind of analyses can we do with these data?

A. Counts by category</br>
B. Average preference</br>
C. Change across time
:::

---

::: {.callout-important}
## Your turn
What kind of visualization(s) can we make with these data?

See the [tutorial](../tutorials/tutorial-making-data.qmd#nominal-data) for more on this topic.
:::


## Today

- Mapping data types to statistics
- Mapping data types to figures

## Goals

- Understand how different data types map to 
  - different types of quantitative summaries
  - different types of data visualizations
- Gain an appreciation of the variety of data visualizations

# Mapping data types to statistics

# Mapping data types to figures

## Considerations

- What figure type(s) are appropriate for the data type
- What figure type(s) are most informative/least misleading

## What did we find?

- [Figures in fields outside of psychology](../supplemental/other-field-figs.qmd)
- [Figures in psychology](../supplemental/psych-sci-figs.qmd)

## What does Google Forms suggest?

# Main points

# Next time

# Resources

## References
