# Outline

## About

This document outlines the major components and themes of the class.

## Week-01
### Course introduction
- People
- Aims/learning goals
- Exercises/evaluation
- Expectations/policies
### Core concepts
- What are data
- Symbols
## Who visualizes data
### Business, industry, government
- Business/industry
- Government
### Science
## Why visualize data
### Explore/understand/analyze

- Exploratory Data Analysis
  - [Chapter 7: Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html) from R for Data Science. The second edition, @Wickham2023-hc, has an accompanying website here: <https://r4ds.hadley.nz>. Chapter 10 contains the [EDA material](https://r4ds.hadley.nz/eda).

### Explain/persuade

## On data

### What are data

- https://towardsdatascience.com/what-is-data-8f94ae3a56b4, @Kozyrkov2019-wl
- @Carlson2007-cb

### Where do data come from?

### Types of data

- Discrete/nominal
  - Yes/no
  - Categorical
- Ordinal
  - Likert scales
  - Rankings
- Interval
  - Time/date ranges
- Continuous/Quantitative
  - Time
  - Space
  - Quantity
  - Ratio vs. Interval
    - Temperature: interval
  
##### Resources

- <https://dept.stat.lsa.umich.edu/~kshedden/introds/topics/types_of_data/>
- <https://www.brookes.ac.uk/students/academic-development/maths-and-stats/statistics/types-of-data>
- <https://en.wikipedia.org/wiki/Data_type>, but targeted to computer science folks.

### Thinking about data

- Distributions
  - Shape
  - Central tendency
  - Spread/outliers
  - Missingness
- Relationships

## Types of figures

- https://www.tableau.com/visualization/what-is-data-visualization

### Relationships

- Mapping information to visual properties

### Conventional

- Maps
- Sports (e.g., football)
  - Football
    - <https://en.wikipedia.org/wiki/American_football_positions>
- Iconic/artistic
  - Dance notation
    - https://www.britannica.com/art/dance-notation/Twentieth-century-developments
  - Musical notation
- Business Process Modeling Notation (BPMN)
  - https://www.visual-paradigm.com/guide/bpmn/bpmn-orchestration-vs-choreography-vs-collaboration/

### Mathematical/Statistical

- Scatterplots
- Bar plots
- Histogram and its variants (violin, boxplot, etc.) to show distributions
- Exploratory data analysis
- Correlation matrices
  - @Kassambara2023-ud

### Networks

#### References

- @Merico2009-tc
- @Morabito-au

### Computer science/engineering

- Database schemas entity/relationship
- User journeys
- Schematics

## Understanding figures

### Perception
### Cognition
### Storytelling

## Critiquing figures

### Lying with statistics (alone)

- Anscombe's Quartet
- Datasaurus

### Aesthetics vs. substance

- Tufte chartjunk, infographics
- Color choices?

#### Substantive

- Predictors vs. outcomes
- Categorical/nominal vs. ordinal vs. continuous

### How to communicate precisely

### Communicating statistical properties

- Trends
- Variation
- Model fits

### How (not) to mislead

>Methodology
Where possible, changes over time and differences across groups are tested for statistical significance. Differences were assessed for statistical significance using statistical testing methods recommended by the individual data systems. Statistical significance is assessed at the 0.05 level without correction for multiple comparisons.
>
>To describe differences across groups, terms such as “similar” and “no difference” are used to indicate that the estimates being compared were not found to be significantly different, while terms such as “higher” or “lower” indicate that a significant difference was detected. Lack of comment regarding the difference between estimates does not necessarily mean that differences were tested and found not to be significant.
>
>To describe trends, terms such as “stable” and “no clear trend” are used to indicate that the slope of the segment was not statistically different from 0, while terms such as “increased” and “decreased” indicate that a significant slope was detected. Since the 2018 publication of the National Center for Health Statistics (NCHS) Guidelines for Analysis of Trends, the Health, United States infographics have adhered to these guidelines in order to analyze trends from NCHS complex sample surveys and the National Vital Statistics System.

From <https://www.cdc.gov/nchs/hus/resources/infographics.htm>.

- APA guidelines

## Gathering data

### Finding data

### Cleaning

## Making figures

### MS Excel

### ggplot2

### matplotib

### JavaScript libraries

#### d3

- https://d3js.org
- https://quarto.org/docs/interactive/ojs/

### Interactive visualizations

- [Plotly-R](https://plotly-r.com/) web book
