# Resources

## About

This page captures some of the resources Rick Gilmore found in developing this course.

::: {.callout-note}
Since I'm having some trouble with cross-references to figures, let's see if they work when we're linking to a figure generated in R:

Does this reference work: @fig-dual-boxplots-diff-ggplot2

And for grins, does the reference to a Python-generated figure work: @fig-multiple-violin-plots

It looks like the answer is no.
:::


## Web sites

### Annual Reviews

Annual Reviews has a great API that lets one search for figures within journals.

- <https://www.annualreviews.org/search?value1=psychology&option1=fulltext&facetOptions=51&value51=%22Figure%22&facetNames=contentType_facet&option51=contentType_facet&operator51=AND>

- <https://www.annualreviews.org/search?value1=neuroscience&option1=fulltext&facetOptions=51&value51=%22Figure%22&facetNames=contentType_facet&option51=contentType_facet&operator51=AND>

Annual Reviews also publishes an electronic magazine, Knowable, that includes a graphics library: <https://www.flickr.com/photos/knowablemag/>

### rpsychologist.com

<@software{magnussonCorrelation,
    author = {Kristoffer Magnusson},
    title = {Interpreting Correlations: An Interactive Visualization},
    url = {https://rpsychologist.com/correlation/},
    version = {0.7.1},
    date = {2023},
  }
  

### https://clauswilke.com/dataviz

- https://clauswilke.com/dataviz/coordinate-systems-axes.html


$10 = 1\times 10$ and $0.1 = 1/10$. The value 0, on the other hand, can never appear on a log scale. It lies infinitely far from 1. One way to see this is to consider that $log(0) = -\infty$. Or, alternatively, consider that to go from 1 to 0, it takes either an infinite number of divisions by a finite value (e.g., $1/10/10/10/10/10/10\dots = 0$) or alternatively one division by infinity (i.e., $1/\infty = 0$).

### DataCamp.com

### Statistical Methods for Data Science

<https://epurdom.github.io/Stat131A/book/>

#### R

- Introduction to R (beginner)
- Introduction to Data Visualization with ggplot2 (beginner)
- Introduction to Exploratory Data Analysis (intermediate)

- Data Visualization with R Track <https://app.datacamp.com/learn/skill-tracks/data-visualization-with-r>
  - 3 courses, 12 hours.
  
#### Python

- Data Visualization in Python Track <https://app.datacamp.com/learn/skill-tracks/data-visualization-with-python>
  - Four courses, 16 hours
  - Introduction to Data Visualization with Matplotlib <https://app.datacamp.com/learn/courses/introduction-to-data-visualization-with-matplotlib>, 4 hours, is the beginning 

### [Data Visualization Society](https://www.datavisualizationsociety.org/)

[Information is Beautiful Awards](https://www.informationisbeautifulawards.com/)

### Friendly's Psychology 6135

Psychology 6135: Psychology of Data Visualization, <http://euclid.psych.yorku.ca/www/psy6135/index.html>, by Michael Friendly at York University.

Here is a more recent version: <https://friendly.github.io/6135/>

Friendly might be a good guest.

<https://nicolas.kruchten.com/semiology_of_graphics/>

### Centers for Disease Control (CDC)

Infographics examples from the CDC: <https://www.cdc.gov/nchs/hus/resources/infographics.htm>

## healthdata.gov

<https://healthdata.gov/browse?limitTo=charts&sortBy=last_modified&utf8=%E2%9C%93&pageSize=20&page=1>

### New York Times

<https://www.nytimes.com/spotlight/graphics>

### The Economist

<https://impact.economist.com/perspectives/search/infographic?f[0]=type%3Ainfographic&f[1]=>

### Nature Publishing

[Figure prep guidelines](https://www.nature.com/documents/natrev-figure-guidelines-v1.pdf)

### American Psychological Association

[Tables and Figures style guide](https://apastyle.apa.org/style-grammar-guidelines/tables-figures)

### Our World In Data

<https://ourworldindata.org/>

### xkcd

<https://xkcd.com/about/>

### Tableau.com

<https://www.tableau.com/sports-data>

### NFL.com

<https://operations.nfl.com/gameday/analytics/stats-articles/>

## Books

- Graphical Data Analysis with R, Antony Unwin, <http://www.gradaanwr.net>

## Papers
