project:
  type: website
  render:
    - "./*.qmd"
    - "tutorials/*.qmd"
    - "surveys/*.qmd"
    - "slides/*.qmd"
  output-dir: "../docs"

website:
  title: "PSYCH 490 • Spr 2025"
  # chapters:
    # - href: index.qmd
    #   text: Overview
    # - href: schedule.qmd
    # - part: Exercises
    #   chapters:
    #     - exercises/exNN-reading-figures.qmd
    # - part: Tutorials
    #   chapters:
    #     - tutorials/tutorial-rstudio-on-pc.qmd
    #     - tutorials/tutorial-rstudio-on-psu.qmd
    #     - tutorials/tutorial-r-ggplot.qmd
    #     - tutorials/tutorial-python-matplotlib.qmd
    # - part: Surveys
    #   chapters:
    #     - surveys/survey-01.qmd
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: schedule.qmd
        text: Schedule
      - href: evaluation.qmd
        text: Evaluation
      - href: deadlines.qmd
        text: Deadlines
      - href: policies.qmd
        text: Policies
      - href: values.qmd
        text: Values
      - text: exercises
        menu: 
          - href: "exercises/ex01-read-a-scientific-paper.qmd"
          - href: "exercises/ex02-textbook-findings.qmd"
      - text: Tutorials
        menu:
        - tutorials/tutorial-rstudio-on-pc.qmd
        - tutorials/tutorial-rstudio-on-psu.qmd
        - tutorials/tutorial-r-ggplot.qmd
        - tutorials/tutorial-python-matplotlib.qmd
      - text: Surveys
        menu:
          - href: "surveys/survey-01.qmd"
            text: "Survey-01"
      - href: resources.qmd
      - href: meta.qmd
  repo-url: https://github.com/psu-psychology/psych-490-data-viz-2025-spring
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    center: "Copyright 2025, Rick Gilmore" 
    right:
      - icon: github
        href: https://github.com/rogilmore
    background: light
format:
  html:
    theme: default
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    # date-modified: last-modified
    bibliography: [include/bib/packages.bib, include/bib/data-viz.bib]
    csl: include/bib/apa.csl
    html-math-method: mathjax
    code-fold: true
    code-tools: true
    toc-depth: 3
    lightbox: true
    
editor: source

jupyter: python3

knitr:
  opts_chunk:
    fig.path: include/fig/
