project:
  type: website
  render:
    - "./*.qmd"
    - "tutorials/*.qmd"
  output-dir: "../docs"

website:
  title: "PSYCH 490 • Spr 2025"
  navbar:
    left:
      - href: index.qmd
      - href: schedule.qmd
        text: Schedule
      - text: Tutorials
        menu:
          - href: "tutorials/tutorial-xx-python-intro.qmd"
      - href: resources.qmd
  repo-url: https://github.com/psu-psychology/psych-490-data-viz-2025-spring
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    center: "Copyright 2025, Rick Gilmore" 
    right:
      - icon: github
        href: https://github.com/rogilmore
    background: light
format:
  html:
    theme: default
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    date-modified: last-modified
    bibliography: [include/bib/packages.bib, include/bib/data-viz.bib]
    csl: include/bib/apa.csl
    html-math-method: mathjax

editor: source

jupyter: python3

knitr:
  opts_chunk:
    fig.path: include/fig/
