project:
  type: website
  render:
    - "./*.qmd"
    - "tutorials/*.qmd"
    - "surveys/*.qmd"
    - "slides/*.qmd"
    - "exercises/*.qmd"
    - "supplemental/*.qmd"
  output-dir: "../docs"

website:
  title: "PSYCH 490 • Spr 25"
  announcement: 
    content: "**No deadlines this week!** | Please complete your classmates' [surveys](https://docs.google.com/spreadsheets/d/1Z-TJQLOQ-yFBs0UimtCtv4pWIqcfq7jhAUA1QjVX89w/edit?usp=sharing)." 
    position: below-navbar
    icon: info-circle
    dismissable: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: evaluation.qmd
        text: Evaluation
      - href: deadlines.qmd
        text: Deadlines
      - href: policies.qmd
        text: "Policies & Values"
      - text: Exercises
        menu: 
        - exercises/ex01-figs-in-psych-sci.qmd
        - exercises/ex02-data-viz-outside-psych.qmd
        - exercises/ex03-making-data.qmd
        - exercises/ex04-sci-of-data-viz.qmd
      - text: Tutorials
        menu:
        - tutorials/tutorial-making-data.qmd
        - tutorials/tutorial-rstudio-on-pc.qmd
        - tutorials/tutorial-rstudio-on-psu.qmd
        - tutorials/tutorial-r-ggplot.qmd
        - tutorials/tutorial-python-matplotlib.qmd
      - text: Supplemental
        menu:
        - href: supplemental/ex01-feedback.qmd
        - href: supplemental/psych-sci-figs.qmd
        - href: supplemental/other-field-figs.qmd
      - href: meta.qmd
  repo-url: https://github.com/psu-psychology/psych-490-data-viz-2025-spring
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright © 2025- Rick Gilmore"
    center: "Built with [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/rogilmore
    background: light
format:
  html:
    theme: default
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    date-modified: last-modified
    date: today
    bibliography: [include/bib/packages.bib, include/bib/data-viz.bib]
    csl: include/bib/apa.csl
    html-math-method: mathjax
    code-fold: true
    code-tools: true
    toc-depth: 3
    lightbox: true
    
editor: source

jupyter: python3

knitr:
  opts_chunk:
    fig.path: include/fig/
