## January 13-17 {- #week-01}

*Surveying the landscape*

### Tuesday, January 14 {-}

*Course introduction*

- [Slides](slides/wk01-2025-01-14-course-intro.qmd)
- [Exercise 01](exercises/ex01-figs-in-psych-sci.qmd) [assigned]{.green_assigned}

### Thursday, January 16 {-}

*The semiotics of data visualization*

- Read: @Cairo2013-hm, Chapter 1-2, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927889)
- [Slides](slides/wk01-2025-01-16-semiotics-data-viz.qmd)

## January 20-24 {- #week-02}

*Who visualizes data and why*

### Tuesday, January 21 {-}

*Visualization in government & business*

- [Slides](slides/wk02-2025-01-21-govt-biz.qmd)
- [Results](supplemental/psych-sci-figs.qmd) from [Exercise 01](exercises/ex01-figs-in-psych-sci.qmd)

### Thursday, January 23 {-}

*Visualization in art, sports, and journalism*

- Read (recommended): @Gelman2013-he
- [Slides](slides/wk02-2025-01-23-art-sports-journ.qmd)
- [Assigned]{.green_assigned}: [Exercise 02](exercises/ex02-data-viz-outside-psych.qmd) 
- [Due]{.orange_due}: [Exercise 01](exercises/ex01-figs-in-psych-sci.qmd) | [Canvas dropbox](https://psu.instructure.com/courses/2381584/assignments/16998394)

## January 27-31 {- #week-03}

*Understanding figures*

### Tuesday, January 28 {-}

*Making (sense of) data*

- Read: @Stevens1946-sh
- Optional: 
  - @Wikipedia-contributors2024-xu
  - @Tourangeau2012-fr | [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=173503626).
- [Slides](slides/wk03-2025-01-28-making-data.qmd)
- [Assigned]{.green_assigned}: [Exercise-03](exercises/ex03-making-data.qmd)

### Thursday, January 30 {-}

*Figure types*

- Explore (pick at least two): 
  - @RibeccaUnknown-tz
  - @Hammond2024-ow
  - @Discovery2024-la
  - @AtlassianUnknown-ob
- Watch: @Channel2024-so
- [Slides](slides/wk03-2025-01-30-figure-types.qmd)
- [Due]{.orange_due}: [Exercise 02](exercises/ex02-data-viz-outside-psych.qmd) | [Canvas dropbox](https://psu.instructure.com/courses/2381584/assignments/16998399) |

## February 3-7 {- #week-04}

### Tuesday, February 04 {-}

*Figure components*

- [Slides](slides/wk04-2025-02-04-figure-components.qmd)
- Review: [Making and visualizing data](tutorials/tutorial-making-data.qmd)

### Thursday, February 06 {-}

**Cancelled due to weather**

## February 10-14 {- #week-05}

### Tuesday, February 11 {-}

*From stimulus to sensation*

- Read: @Cairo2013-hm, Chapter 5, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927892)
- [Slides](slides/wk05-2025-02-11-stim-to-sensation.qmd)
- [Due]{.orange_due}: [Exercise-03](exercises/ex03-making-data.qmd) | [Canvas dropbox](https://psu.instructure.com/courses/2381584/assignments/16998400) |

### Thursday, February 13 {-}

*From sensation to perception*

- Read: 
    - @Cairo2013-hm, Chapter 6, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927892)
    - @Stephen-Few2004-jv, Chapter 5, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=174195660)
- Optional:
    - @Cleveland1984-py
- [Slides](slides/wk05-2025-02-13-sensation-to-perception.qmd)

## February 17-21 {- #week-06}

### Tuesday, February 18 {-}

*From cognition to understanding*

 - Read:
    - @Franconeri2021-uv, pp. 109-122, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=174557876)
    - @Cairo2013-hm, Chapter 7, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927892)
- [Slides](slides/wk06-2025-02-18-cognition-to-understanding.qmd)
- [Assigned]{.green_assigned}: [Final Project](exercises/final-project.qmd) proposal

### Thursday, February 20 {-}

*Designing efficient & understandable visualizations*

- Read: @Franconeri2021-uv, pp. 123-139, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=174557876)
- [Slides](slides/wk06-2025-02-20-designing-viz.qmd)
- [Assigned]{.green_assigned}: [Exercise-04](exercises/ex04-sci-of-data-viz.qmd)

## February 24-28 {- #week-07}

### Tuesday, February 25 {-}

*Introduction to R*

- [Slides](slides/wk07-2025-02-25-intro-to-r.qmd)
- [Sign up](https://www.datacamp.com/groups/shared_links/a4e4322254cc9e99082294b2f5eb9b0af748f1d42907df9f716475be78a0520c) for DataCamp.
- Begin work on Introduction to R.

### Thursday, February 27 {-}

*Communicating uncertainty and risk*  

- Read: @Franconeri2021-uv, pp. 139-150, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=174557876)
- [Slides](slides/wk07-2025-02-27-viz-uncertainty-risk.qmd)
- In-class work on [Exercise 04](exercises/ex04-sci-of-data-viz.qmd), [Final Project proposal](exercises/final-project.qmd), or [DataCamp](https://datacamp.com)

<!-- *Storytelling with data* -->

<!-- - Read:  -->
<!--     - @Knaflic2015-wq, pp. ix-33, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927897) -->
<!--     - @Knaflic2015-wq, pp. 33-69, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927897) -->
<!-- - Skim: @Woodside2008-yv -->

## March 3-7 {- #week-08}

### Tuesday, March 04 {-}

*More Slow-R*

- Read: 
    - Gilmore 2019 ["Slow R"](https://psu-psychology.github.io/r-bootcamp-2019/talks/slow-r.html)
- [Slides](slides/wk08-2025-03-04-more-slow-r.qmd)
- Work on: Datacamp Introduction to R. 
- In-class work on [Exercise 04](exercises/ex04-sci-of-data-viz.qmd), [Final Project proposal](exercises/final-project.qmd), or [DataCamp](https://datacamp.com)

### Thursday, March 06 {-}

<!-- No Sara -->
<!-- *Exploring data* -->
<!-- - Read: @Tukey1977-ro, Chapter 1, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927904) -->

*Critiquing figures*

- Read: 
    - @Tufte2001-cb, Chapter 1, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927901)
    - @Tufte2001-cb, Chapter 2, [PDF on Canvas](https://psu.instructure.com/courses/2381584/files?preview=172927901)
- [Slides](slides/wk08-2025-03-06-critiquing-figs.qmd)
- [Due]{.orange_due}: [Exercise-04](exercises/ex04-sci-of-data-viz.qmd) | [Canvas Dropbox](https://psu.instructure.com/courses/2381584/assignments/16998405)
- [Assigned]{.green_assigned}: [Exercise-05](exercises/ex05-figure-prep-guidelines.qmd)
- [Due]{.orange_due}: [Final Project](exercises/final-project.qmd) proposal | [Canvas Dropbox](https://psu.instructure.com/courses/2381584/assignments/16998415)

## March 10-14 *Spring Break* {- #spring-break}

## March 17-21 {- #week-09}

### Tuesday, March 18 {-}

*Why R we doing this?*

- Complete:
  - DataCamp, Introduction to R
- [Slides](slides/wk09-2025-03-18-why-r.qmd)

### Thursday, March 20 {-}

**NO CLASS**

- [Due]{.orange_due}: [Exercise-05](exercises/ex05-figure-prep-guidelines.qmd)

## March 24-28 {- #week-10}

*Exploring data with R*

### Tuesday, March 25 {-}

*Gathering & cleaning data*

- [Slides](slides/wk10-2025-03-25-gathering-cleaning.qmd)

### Thursday, March 27 {-}

*Making plots with `ggplot2`*

- Read:
  - [*Plotting with `ggplot2`*](tutorials/tutorial-r-ggplot.qmd), especially the ["Plotting one variable" ](tutorials/tutorial-r-ggplot.qmd#plotting-one-variable) section.
- Recommended: 
  - [Introduction to Data Visualization with ggplot2](https://app.datacamp.com/groups/psych-490-the-psychology-of-data-visualization/assignments/325606) on DataCamp
- [Slides](slides/wk10-2025-03-27-making-plots.qmd)
- [Assigned]{.green_assigned}: [Exercise-06](exercises/ex06-figs-w-r.qmd)

## March 31 - April 4 {- #week-11}

*Introduction to Python*

### Tuesday, April 01 {-}

- [Assigned]{.green_assigned}: Final project [preferences survey](https://forms.gle/oyotxgnnqchqnSgTA)

### Thursday, April 03 {-}

- [Due]{.orange_due}: [Exercise-06](exercises/ex06-figs-w-r.qmd)

## April 7-11 {- #week-12}

*Exploring data with Python*

### Tuesday, April 08 {-}

- [Due]{.orange_due}: Final project [preferences survey](https://forms.gle/oyotxgnnqchqnSgTA)

### Thursday, April 10 {-}

- [Assigned]{.green_assigned}: [Exercise-07](exercises/ex07-figs-w-python.qmd)

## April 14-18 {- #week-13}

*Making plots with JavaScript*

### Tuesday, April 15 {-}

### Thursday, April 17 {-}

- [Due]{.orange_due}: [Exercise-07](exercises/ex07-figs-w-python.qmd)

## April 21-25 {- #week-14}

*Final Project Preparation*

### Tuesday, April 22 {-}

- In-class work on projects.

### Thursday, April 24 {-}

- In-class work on projects.

## April 28 - May 2 {- #week-15}

*Final Project Presentations*

### Tuesday, April 29 {-}

- Schedule: TBD^[To be determined]

### Thursday, May 01 {-}

- Schedule: TBD

## May 5-9 {- #finals-week}

*Finals Week*

### Tuesday, May 05 {-}

- [Due]{.orange_due}: [Final project](exercises/final-project.qmd) write-up
